version: '3.8'

services:
  ml-pipeline:
    build: .
    container_name: ml-pipeline
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCS_RAW_DATA_BUCKET=${GCS_RAW_DATA_BUCKET}
      - GCS_PROCESSED_DATA_BUCKET=${GCS_PROCESSED_DATA_BUCKET}
      - GCS_MODEL_BUCKET=${GCS_MODEL_BUCKET}
      - VERTEX_AI_REGION=${VERTEX_AI_REGION}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./pipeline_data:/app/pipeline_data
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    command: python run_complete_pipeline.py
    
  data-pipeline:
    build: .
    container_name: data-pipeline
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCS_RAW_DATA_BUCKET=${GCS_RAW_DATA_BUCKET}
      - GCS_PROCESSED_DATA_BUCKET=${GCS_PROCESSED_DATA_BUCKET}
      - GCS_MODEL_BUCKET=${GCS_MODEL_BUCKET}
      - VERTEX_AI_REGION=${VERTEX_AI_REGION}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./pipeline_data:/app/pipeline_data
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    command: python run_data_pipeline.py
    
  training-pipeline:
    build: .
    container_name: training-pipeline
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCS_RAW_DATA_BUCKET=${GCS_RAW_DATA_BUCKET}
      - GCS_PROCESSED_DATA_BUCKET=${GCS_PROCESSED_DATA_BUCKET}
      - GCS_MODEL_BUCKET=${GCS_MODEL_BUCKET}
      - VERTEX_AI_REGION=${VERTEX_AI_REGION}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./pipeline_data:/app/pipeline_data
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    command: python run_train_pipeline.py